// Package swagger provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package swagger

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AddGroupUserRequestDto defines model for AddGroupUserRequestDto.
type AddGroupUserRequestDto struct {
	TelegramId *int64 `json:"telegramId,omitempty"`
}

// BalanceResponseDto defines model for BalanceResponseDto.
type BalanceResponseDto struct {
	Balances *[]UserBalanceResponseDto `json:"balances"`
}

// CreateDirectPaymentRequestDto defines model for CreateDirectPaymentRequestDto.
type CreateDirectPaymentRequestDto struct {
	Amount     *float64            `json:"amount,omitempty"`
	FromUserId *openapi_types.UUID `json:"fromUserId,omitempty"`
	ToUserId   *openapi_types.UUID `json:"toUserId,omitempty"`
}

// CreateExpenseRequestDto defines model for CreateExpenseRequestDto.
type CreateExpenseRequestDto struct {
	CreatedById *openapi_types.UUID      `json:"createdById,omitempty"`
	IsDraft     *bool                    `json:"isDraft,omitempty"`
	Shares      *[]ExpenseShareCreateDto `json:"shares"`
	Title       *string                  `json:"title"`
	TotalAmount *float64                 `json:"totalAmount,omitempty"`
}

// CreateGroupRequestDto defines model for CreateGroupRequestDto.
type CreateGroupRequestDto struct {
	CreatedByTelegramId *int64  `json:"createdByTelegramId,omitempty"`
	TelegramChatId      *int64  `json:"telegramChatId"`
	Title               *string `json:"title"`
}

// CreatePaymentForExpenseRequestDto defines model for CreatePaymentForExpenseRequestDto.
type CreatePaymentForExpenseRequestDto struct {
	Amount     *float64            `json:"amount,omitempty"`
	ExpenseId  *openapi_types.UUID `json:"expenseId,omitempty"`
	FromUserId *openapi_types.UUID `json:"fromUserId,omitempty"`
}

// ExpenseResponseDto defines model for ExpenseResponseDto.
type ExpenseResponseDto struct {
	CreatedAt   *time.Time                 `json:"createdAt,omitempty"`
	CreatedById *openapi_types.UUID        `json:"createdById,omitempty"`
	Id          *openapi_types.UUID        `json:"id,omitempty"`
	IsDraft     *bool                      `json:"isDraft,omitempty"`
	Shares      *[]ExpenseShareResponseDto `json:"shares"`
	Title       *string                    `json:"title"`
	TotalAmount *float64                   `json:"totalAmount,omitempty"`
}

// ExpenseShareCreateDto defines model for ExpenseShareCreateDto.
type ExpenseShareCreateDto struct {
	Amount *float64            `json:"amount,omitempty"`
	UserId *openapi_types.UUID `json:"userId,omitempty"`
}

// ExpenseShareResponseDto defines model for ExpenseShareResponseDto.
type ExpenseShareResponseDto struct {
	Amount *float64            `json:"amount,omitempty"`
	IsPaid *bool               `json:"isPaid,omitempty"`
	UserId *openapi_types.UUID `json:"userId,omitempty"`
}

// GroupOverviewResponseDto defines model for GroupOverviewResponseDto.
type GroupOverviewResponseDto struct {
	Id    *openapi_types.UUID `json:"id,omitempty"`
	Title *string             `json:"title"`
}

// GroupResponseDto defines model for GroupResponseDto.
type GroupResponseDto struct {
	Id             *openapi_types.UUID `json:"id,omitempty"`
	TelegramChatId *int64              `json:"telegramChatId"`
	Title          *string             `json:"title"`
	Users          *[]UserResponseDto  `json:"users"`
}

// OperationHistoryResponseDto defines model for OperationHistoryResponseDto.
type OperationHistoryResponseDto struct {
	Description     *string             `json:"description"`
	Id              *openapi_types.UUID `json:"id,omitempty"`
	InitiatorUserId *openapi_types.UUID `json:"initiatorUserId,omitempty"`
	Timestamp       *time.Time          `json:"timestamp,omitempty"`
	Type            *string             `json:"type"`
}

// PaymentResponseDto defines model for PaymentResponseDto.
type PaymentResponseDto struct {
	Amount     *float64            `json:"amount,omitempty"`
	ExpenseId  *openapi_types.UUID `json:"expenseId"`
	FromUserId *openapi_types.UUID `json:"fromUserId,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	Timestamp  *time.Time          `json:"timestamp,omitempty"`
	ToUserId   *openapi_types.UUID `json:"toUserId,omitempty"`
}

// TransferSuggestionDto defines model for TransferSuggestionDto.
type TransferSuggestionDto struct {
	Amount     *float64            `json:"amount,omitempty"`
	FromUserId *openapi_types.UUID `json:"fromUserId,omitempty"`
	ToUserId   *openapi_types.UUID `json:"toUserId,omitempty"`
}

// TransferSuggestionsResponseDto defines model for TransferSuggestionsResponseDto.
type TransferSuggestionsResponseDto struct {
	Transfers *[]TransferSuggestionDto `json:"transfers"`
}

// UpdateExpenseRequestDto defines model for UpdateExpenseRequestDto.
type UpdateExpenseRequestDto struct {
	IsDraft     *bool                    `json:"isDraft"`
	Shares      *[]ExpenseShareCreateDto `json:"shares"`
	Title       *string                  `json:"title"`
	TotalAmount *float64                 `json:"totalAmount"`
}

// UpdateGroupRequestDto defines model for UpdateGroupRequestDto.
type UpdateGroupRequestDto struct {
	Title *string `json:"title"`
}

// UpdatePaymentRequestDto defines model for UpdatePaymentRequestDto.
type UpdatePaymentRequestDto struct {
	Amount *float64 `json:"amount,omitempty"`
}

// UpdateUserRequestDto defines model for UpdateUserRequestDto.
type UpdateUserRequestDto struct {
	DisplayName *string `json:"displayName"`
}

// UserBalanceResponseDto defines model for UserBalanceResponseDto.
type UserBalanceResponseDto struct {
	Balance *float64            `json:"balance,omitempty"`
	UserId  *openapi_types.UUID `json:"userId,omitempty"`
}

// UserCreateRequestDto defines model for UserCreateRequestDto.
type UserCreateRequestDto struct {
	DisplayName *string             `json:"displayName"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	TelegramId  *int64              `json:"telegramId,omitempty"`
}

// UserOverviewResponseDto defines model for UserOverviewResponseDto.
type UserOverviewResponseDto struct {
	DisplayName *string             `json:"displayName"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	TelegramId  *int64              `json:"telegramId,omitempty"`
}

// UserResponseDto defines model for UserResponseDto.
type UserResponseDto struct {
	DisplayName *string             `json:"displayName"`
	Groups      *[]GroupResponseDto `json:"groups"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	TelegramId  *int64              `json:"telegramId,omitempty"`
}

// GetApiGroupsParams defines parameters for GetApiGroups.
type GetApiGroupsParams struct {
	// UserTelegramId Telegram ID of the user.
	UserTelegramId *int64 `form:"userTelegramId,omitempty" json:"userTelegramId,omitempty"`
}

// GetApiGroupsGroupIdExpensesParams defines parameters for GetApiGroupsGroupIdExpenses.
type GetApiGroupsGroupIdExpensesParams struct {
	// UserId Optional user ID to filter expenses by payer.
	UserId *openapi_types.UUID `form:"userId,omitempty" json:"userId,omitempty"`
}

// GetApiGroupsGroupIdTransfersParams defines parameters for GetApiGroupsGroupIdTransfers.
type GetApiGroupsGroupIdTransfersParams struct {
	// UseNpAlgorithm If true, use the NP-complete optimization algorithm for minimal transactions;
	// otherwise use the greedy algorithm.
	UseNpAlgorithm *bool `form:"useNpAlgorithm,omitempty" json:"useNpAlgorithm,omitempty"`
}

// PostApiGroupsApplicationWildcardPlusJSONRequestBody defines body for PostApiGroups for application/*+json ContentType.
type PostApiGroupsApplicationWildcardPlusJSONRequestBody = CreateGroupRequestDto

// PostApiGroupsJSONRequestBody defines body for PostApiGroups for application/json ContentType.
type PostApiGroupsJSONRequestBody = CreateGroupRequestDto

// PutApiGroupsGroupIdApplicationWildcardPlusJSONRequestBody defines body for PutApiGroupsGroupId for application/*+json ContentType.
type PutApiGroupsGroupIdApplicationWildcardPlusJSONRequestBody = UpdateGroupRequestDto

// PutApiGroupsGroupIdJSONRequestBody defines body for PutApiGroupsGroupId for application/json ContentType.
type PutApiGroupsGroupIdJSONRequestBody = UpdateGroupRequestDto

// PostApiGroupsGroupIdExpensesApplicationWildcardPlusJSONRequestBody defines body for PostApiGroupsGroupIdExpenses for application/*+json ContentType.
type PostApiGroupsGroupIdExpensesApplicationWildcardPlusJSONRequestBody = CreateExpenseRequestDto

// PostApiGroupsGroupIdExpensesJSONRequestBody defines body for PostApiGroupsGroupIdExpenses for application/json ContentType.
type PostApiGroupsGroupIdExpensesJSONRequestBody = CreateExpenseRequestDto

// PutApiGroupsGroupIdExpensesExpenseIdApplicationWildcardPlusJSONRequestBody defines body for PutApiGroupsGroupIdExpensesExpenseId for application/*+json ContentType.
type PutApiGroupsGroupIdExpensesExpenseIdApplicationWildcardPlusJSONRequestBody = UpdateExpenseRequestDto

// PutApiGroupsGroupIdExpensesExpenseIdJSONRequestBody defines body for PutApiGroupsGroupIdExpensesExpenseId for application/json ContentType.
type PutApiGroupsGroupIdExpensesExpenseIdJSONRequestBody = UpdateExpenseRequestDto

// PostApiGroupsGroupIdExpensesExpenseIdParticipantsApplicationWildcardPlusJSONRequestBody defines body for PostApiGroupsGroupIdExpensesExpenseIdParticipants for application/*+json ContentType.
type PostApiGroupsGroupIdExpensesExpenseIdParticipantsApplicationWildcardPlusJSONRequestBody = ExpenseShareCreateDto

// PostApiGroupsGroupIdExpensesExpenseIdParticipantsJSONRequestBody defines body for PostApiGroupsGroupIdExpensesExpenseIdParticipants for application/json ContentType.
type PostApiGroupsGroupIdExpensesExpenseIdParticipantsJSONRequestBody = ExpenseShareCreateDto

// PutApiGroupsGroupIdExpensesExpenseIdParticipantsUserIdApplicationWildcardPlusJSONRequestBody defines body for PutApiGroupsGroupIdExpensesExpenseIdParticipantsUserId for application/*+json ContentType.
type PutApiGroupsGroupIdExpensesExpenseIdParticipantsUserIdApplicationWildcardPlusJSONRequestBody = ExpenseShareCreateDto

// PutApiGroupsGroupIdExpensesExpenseIdParticipantsUserIdJSONRequestBody defines body for PutApiGroupsGroupIdExpensesExpenseIdParticipantsUserId for application/json ContentType.
type PutApiGroupsGroupIdExpensesExpenseIdParticipantsUserIdJSONRequestBody = ExpenseShareCreateDto

// PostApiGroupsGroupIdPaymentsDirectApplicationWildcardPlusJSONRequestBody defines body for PostApiGroupsGroupIdPaymentsDirect for application/*+json ContentType.
type PostApiGroupsGroupIdPaymentsDirectApplicationWildcardPlusJSONRequestBody = CreateDirectPaymentRequestDto

// PostApiGroupsGroupIdPaymentsDirectJSONRequestBody defines body for PostApiGroupsGroupIdPaymentsDirect for application/json ContentType.
type PostApiGroupsGroupIdPaymentsDirectJSONRequestBody = CreateDirectPaymentRequestDto

// PostApiGroupsGroupIdPaymentsExpenseApplicationWildcardPlusJSONRequestBody defines body for PostApiGroupsGroupIdPaymentsExpense for application/*+json ContentType.
type PostApiGroupsGroupIdPaymentsExpenseApplicationWildcardPlusJSONRequestBody = CreatePaymentForExpenseRequestDto

// PostApiGroupsGroupIdPaymentsExpenseJSONRequestBody defines body for PostApiGroupsGroupIdPaymentsExpense for application/json ContentType.
type PostApiGroupsGroupIdPaymentsExpenseJSONRequestBody = CreatePaymentForExpenseRequestDto

// PutApiGroupsGroupIdPaymentsPaymentIdApplicationWildcardPlusJSONRequestBody defines body for PutApiGroupsGroupIdPaymentsPaymentId for application/*+json ContentType.
type PutApiGroupsGroupIdPaymentsPaymentIdApplicationWildcardPlusJSONRequestBody = UpdatePaymentRequestDto

// PutApiGroupsGroupIdPaymentsPaymentIdJSONRequestBody defines body for PutApiGroupsGroupIdPaymentsPaymentId for application/json ContentType.
type PutApiGroupsGroupIdPaymentsPaymentIdJSONRequestBody = UpdatePaymentRequestDto

// PostApiGroupsGroupIdUsersApplicationWildcardPlusJSONRequestBody defines body for PostApiGroupsGroupIdUsers for application/*+json ContentType.
type PostApiGroupsGroupIdUsersApplicationWildcardPlusJSONRequestBody = AddGroupUserRequestDto

// PostApiGroupsGroupIdUsersJSONRequestBody defines body for PostApiGroupsGroupIdUsers for application/json ContentType.
type PostApiGroupsGroupIdUsersJSONRequestBody = AddGroupUserRequestDto

// PostApiUsersApplicationWildcardPlusJSONRequestBody defines body for PostApiUsers for application/*+json ContentType.
type PostApiUsersApplicationWildcardPlusJSONRequestBody = UserCreateRequestDto

// PostApiUsersJSONRequestBody defines body for PostApiUsers for application/json ContentType.
type PostApiUsersJSONRequestBody = UserCreateRequestDto

// PutApiUsersUserIdApplicationWildcardPlusJSONRequestBody defines body for PutApiUsersUserId for application/*+json ContentType.
type PutApiUsersUserIdApplicationWildcardPlusJSONRequestBody = UpdateUserRequestDto

// PutApiUsersUserIdJSONRequestBody defines body for PutApiUsersUserId for application/json ContentType.
type PutApiUsersUserIdJSONRequestBody = UpdateUserRequestDto
