// Package swagger provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package swagger

import (
	"encoding/json"
	"fmt"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AddGroupUserRequestDto defines model for AddGroupUserRequestDto.
type AddGroupUserRequestDto struct {
	TelegramId *int64 `json:"telegramId,omitempty"`
}

// BalanceResponseDto defines model for BalanceResponseDto.
type BalanceResponseDto struct {
	Balances *[]UserBalanceResponseDto `json:"balances"`
}

// CreateDirectPaymentRequestDto defines model for CreateDirectPaymentRequestDto.
type CreateDirectPaymentRequestDto struct {
	Amount     *float64            `json:"amount,omitempty"`
	FromUserId *openapi_types.UUID `json:"fromUserId,omitempty"`
	ToUserId   *openapi_types.UUID `json:"toUserId,omitempty"`
}

// CreateExpenseRequestDto defines model for CreateExpenseRequestDto.
type CreateExpenseRequestDto struct {
	CreatedById *openapi_types.UUID      `json:"createdById,omitempty"`
	IsDraft     *bool                    `json:"isDraft,omitempty"`
	Shares      *[]ExpenseShareCreateDto `json:"shares"`
	Title       *string                  `json:"title"`
	TotalAmount *float64                 `json:"totalAmount,omitempty"`
}

// CreateGroupRequestDto defines model for CreateGroupRequestDto.
type CreateGroupRequestDto struct {
	CreatedByTelegramId *int64  `json:"createdByTelegramId,omitempty"`
	TelegramChatId      *int64  `json:"telegramChatId"`
	Title               *string `json:"title"`
}

// CreatePaymentForExpenseRequestDto defines model for CreatePaymentForExpenseRequestDto.
type CreatePaymentForExpenseRequestDto struct {
	Amount     *float64            `json:"amount,omitempty"`
	ExpenseId  *openapi_types.UUID `json:"expenseId,omitempty"`
	FromUserId *openapi_types.UUID `json:"fromUserId,omitempty"`
}

// ExpenseResponseDto defines model for ExpenseResponseDto.
type ExpenseResponseDto struct {
	CreatedAt   *time.Time                 `json:"createdAt,omitempty"`
	CreatedById *openapi_types.UUID        `json:"createdById,omitempty"`
	Id          *openapi_types.UUID        `json:"id,omitempty"`
	IsDraft     *bool                      `json:"isDraft,omitempty"`
	Shares      *[]ExpenseShareResponseDto `json:"shares"`
	Title       *string                    `json:"title"`
	TotalAmount *float64                   `json:"totalAmount,omitempty"`
}

// ExpenseShareCreateDto defines model for ExpenseShareCreateDto.
type ExpenseShareCreateDto struct {
	Amount *float64            `json:"amount,omitempty"`
	UserId *openapi_types.UUID `json:"userId,omitempty"`
}

// ExpenseShareResponseDto defines model for ExpenseShareResponseDto.
type ExpenseShareResponseDto struct {
	Amount *float64            `json:"amount,omitempty"`
	IsPaid *bool               `json:"isPaid,omitempty"`
	UserId *openapi_types.UUID `json:"userId,omitempty"`
}

// GroupOverviewResponseDto defines model for GroupOverviewResponseDto.
type GroupOverviewResponseDto struct {
	Id    *openapi_types.UUID `json:"id,omitempty"`
	Title *string             `json:"title"`
}

// GroupResponseDto defines model for GroupResponseDto.
type GroupResponseDto struct {
	Id             *openapi_types.UUID `json:"id,omitempty"`
	TelegramChatId *int64              `json:"telegramChatId"`
	Title          *string             `json:"title"`
	Users          *[]UserResponseDto  `json:"users"`
}

// OperationHistoryResponseDto defines model for OperationHistoryResponseDto.
type OperationHistoryResponseDto struct {
	Description     *string             `json:"description"`
	Id              *openapi_types.UUID `json:"id,omitempty"`
	InitiatorUserId *openapi_types.UUID `json:"initiatorUserId,omitempty"`
	Timestamp       *time.Time          `json:"timestamp,omitempty"`
	Type            *string             `json:"type"`
}

// PaymentResponseDto defines model for PaymentResponseDto.
type PaymentResponseDto struct {
	Amount     *float64            `json:"amount,omitempty"`
	ExpenseId  *openapi_types.UUID `json:"expenseId"`
	FromUserId *openapi_types.UUID `json:"fromUserId,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	Timestamp  *time.Time          `json:"timestamp,omitempty"`
	ToUserId   *openapi_types.UUID `json:"toUserId,omitempty"`
}

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	Detail               *string                `json:"detail"`
	Instance             *string                `json:"instance"`
	Status               *int32                 `json:"status"`
	Title                *string                `json:"title"`
	Type                 *string                `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// TransferSuggestionDto defines model for TransferSuggestionDto.
type TransferSuggestionDto struct {
	Amount     *float64            `json:"amount,omitempty"`
	FromUserId *openapi_types.UUID `json:"fromUserId,omitempty"`
	ToUserId   *openapi_types.UUID `json:"toUserId,omitempty"`
}

// TransferSuggestionsResponseDto defines model for TransferSuggestionsResponseDto.
type TransferSuggestionsResponseDto struct {
	Transfers *[]TransferSuggestionDto `json:"transfers"`
}

// UpdateGroupRequestDto defines model for UpdateGroupRequestDto.
type UpdateGroupRequestDto struct {
	Title *string `json:"title"`
}

// UpdatePaymentRequestDto defines model for UpdatePaymentRequestDto.
type UpdatePaymentRequestDto struct {
	Amount *float64 `json:"amount,omitempty"`
}

// UpdateUserRequestDto defines model for UpdateUserRequestDto.
type UpdateUserRequestDto struct {
	DisplayName *string `json:"displayName"`
}

// UserBalanceResponseDto defines model for UserBalanceResponseDto.
type UserBalanceResponseDto struct {
	Balance *float64            `json:"balance,omitempty"`
	UserId  *openapi_types.UUID `json:"userId,omitempty"`
}

// UserCreateRequestDto defines model for UserCreateRequestDto.
type UserCreateRequestDto struct {
	DisplayName *string `json:"displayName"`
	TelegramId  *int64  `json:"telegramId,omitempty"`
}

// UserOverviewResponseDto defines model for UserOverviewResponseDto.
type UserOverviewResponseDto struct {
	DisplayName *string             `json:"displayName"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	TelegramId  *int64              `json:"telegramId,omitempty"`
}

// UserResponseDto defines model for UserResponseDto.
type UserResponseDto struct {
	DisplayName *string             `json:"displayName"`
	Groups      *[]GroupResponseDto `json:"groups"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	TelegramId  *int64              `json:"telegramId,omitempty"`
}

// GetApiExpensesGroupGroupIdParams defines parameters for GetApiExpensesGroupGroupId.
type GetApiExpensesGroupGroupIdParams struct {
	// UserId Optional user ID to filter expenses by payer.
	UserId *openapi_types.UUID `form:"userId,omitempty" json:"userId,omitempty"`
}

// DeleteApiExpensesExpenseIdParams defines parameters for DeleteApiExpensesExpenseId.
type DeleteApiExpensesExpenseIdParams struct {
	// GroupId ID of the group.
	GroupId *openapi_types.UUID `form:"groupId,omitempty" json:"groupId,omitempty"`
}

// GetApiExpensesExpenseIdParams defines parameters for GetApiExpensesExpenseId.
type GetApiExpensesExpenseIdParams struct {
	// GroupId ID of the group.
	GroupId *openapi_types.UUID `form:"groupId,omitempty" json:"groupId,omitempty"`
}

// GetApiExpensesExpenseIdParticipantsParams defines parameters for GetApiExpensesExpenseIdParticipants.
type GetApiExpensesExpenseIdParticipantsParams struct {
	// GroupId ID of the group.
	GroupId *openapi_types.UUID `form:"groupId,omitempty" json:"groupId,omitempty"`
}

// PostApiExpensesExpenseIdParticipantsParams defines parameters for PostApiExpensesExpenseIdParticipants.
type PostApiExpensesExpenseIdParticipantsParams struct {
	// GroupId ID of the group.
	GroupId *openapi_types.UUID `form:"groupId,omitempty" json:"groupId,omitempty"`
}

// PutApiExpensesExpenseIdParticipantsParams defines parameters for PutApiExpensesExpenseIdParticipants.
type PutApiExpensesExpenseIdParticipantsParams struct {
	// GroupId ID of the group.
	GroupId *openapi_types.UUID `form:"groupId,omitempty" json:"groupId,omitempty"`
}

// DeleteApiExpensesExpenseIdParticipantsUserIdParams defines parameters for DeleteApiExpensesExpenseIdParticipantsUserId.
type DeleteApiExpensesExpenseIdParticipantsUserIdParams struct {
	// GroupId ID of the group.
	GroupId *openapi_types.UUID `form:"groupId,omitempty" json:"groupId,omitempty"`
}

// PutApiExpensesExpenseIdTitleApplicationWildcardPlusJSONBody defines parameters for PutApiExpensesExpenseIdTitle.
type PutApiExpensesExpenseIdTitleApplicationWildcardPlusJSONBody = string

// PutApiExpensesExpenseIdTitleJSONBody defines parameters for PutApiExpensesExpenseIdTitle.
type PutApiExpensesExpenseIdTitleJSONBody = string

// PutApiExpensesExpenseIdTotalAmountApplicationWildcardPlusJSONBody defines parameters for PutApiExpensesExpenseIdTotalAmount.
type PutApiExpensesExpenseIdTotalAmountApplicationWildcardPlusJSONBody = float64

// PutApiExpensesExpenseIdTotalAmountJSONBody defines parameters for PutApiExpensesExpenseIdTotalAmount.
type PutApiExpensesExpenseIdTotalAmountJSONBody = float64

// GetApiGroupsParams defines parameters for GetApiGroups.
type GetApiGroupsParams struct {
	TelegramChatId *int64 `form:"telegramChatId,omitempty" json:"telegramChatId,omitempty"`
}

// GetApiGroupsMyParams defines parameters for GetApiGroupsMy.
type GetApiGroupsMyParams struct {
	// UserTelegramId Telegram ID of the user.
	UserTelegramId *int64 `form:"userTelegramId,omitempty" json:"userTelegramId,omitempty"`
}

// GetApiGroupsGroupIdTransfersParams defines parameters for GetApiGroupsGroupIdTransfers.
type GetApiGroupsGroupIdTransfersParams struct {
	// UseNpAlgorithm If true, use the NP-complete optimization algorithm for minimal transactions;
	// otherwise use the greedy algorithm.
	UseNpAlgorithm *bool `form:"useNpAlgorithm,omitempty" json:"useNpAlgorithm,omitempty"`
}

// GetApiUsersFindParams defines parameters for GetApiUsersFind.
type GetApiUsersFindParams struct {
	// Nickname of the user.
	Nickname       *string `form:"nickname,omitempty" json:"nickname,omitempty"`
	UserTelegramId *int64  `form:"userTelegramId,omitempty" json:"userTelegramId,omitempty"`
}

// PostApiExpensesGroupGroupIdApplicationWildcardPlusJSONRequestBody defines body for PostApiExpensesGroupGroupId for application/*+json ContentType.
type PostApiExpensesGroupGroupIdApplicationWildcardPlusJSONRequestBody = CreateExpenseRequestDto

// PostApiExpensesGroupGroupIdJSONRequestBody defines body for PostApiExpensesGroupGroupId for application/json ContentType.
type PostApiExpensesGroupGroupIdJSONRequestBody = CreateExpenseRequestDto

// PostApiExpensesExpenseIdParticipantsApplicationWildcardPlusJSONRequestBody defines body for PostApiExpensesExpenseIdParticipants for application/*+json ContentType.
type PostApiExpensesExpenseIdParticipantsApplicationWildcardPlusJSONRequestBody = ExpenseShareCreateDto

// PostApiExpensesExpenseIdParticipantsJSONRequestBody defines body for PostApiExpensesExpenseIdParticipants for application/json ContentType.
type PostApiExpensesExpenseIdParticipantsJSONRequestBody = ExpenseShareCreateDto

// PutApiExpensesExpenseIdParticipantsApplicationWildcardPlusJSONRequestBody defines body for PutApiExpensesExpenseIdParticipants for application/*+json ContentType.
type PutApiExpensesExpenseIdParticipantsApplicationWildcardPlusJSONRequestBody = ExpenseShareCreateDto

// PutApiExpensesExpenseIdParticipantsJSONRequestBody defines body for PutApiExpensesExpenseIdParticipants for application/json ContentType.
type PutApiExpensesExpenseIdParticipantsJSONRequestBody = ExpenseShareCreateDto

// PutApiExpensesExpenseIdTitleApplicationWildcardPlusJSONRequestBody defines body for PutApiExpensesExpenseIdTitle for application/*+json ContentType.
type PutApiExpensesExpenseIdTitleApplicationWildcardPlusJSONRequestBody = PutApiExpensesExpenseIdTitleApplicationWildcardPlusJSONBody

// PutApiExpensesExpenseIdTitleJSONRequestBody defines body for PutApiExpensesExpenseIdTitle for application/json ContentType.
type PutApiExpensesExpenseIdTitleJSONRequestBody = PutApiExpensesExpenseIdTitleJSONBody

// PutApiExpensesExpenseIdTotalAmountApplicationWildcardPlusJSONRequestBody defines body for PutApiExpensesExpenseIdTotalAmount for application/*+json ContentType.
type PutApiExpensesExpenseIdTotalAmountApplicationWildcardPlusJSONRequestBody = PutApiExpensesExpenseIdTotalAmountApplicationWildcardPlusJSONBody

// PutApiExpensesExpenseIdTotalAmountJSONRequestBody defines body for PutApiExpensesExpenseIdTotalAmount for application/json ContentType.
type PutApiExpensesExpenseIdTotalAmountJSONRequestBody = PutApiExpensesExpenseIdTotalAmountJSONBody

// PostApiGroupsApplicationWildcardPlusJSONRequestBody defines body for PostApiGroups for application/*+json ContentType.
type PostApiGroupsApplicationWildcardPlusJSONRequestBody = CreateGroupRequestDto

// PostApiGroupsJSONRequestBody defines body for PostApiGroups for application/json ContentType.
type PostApiGroupsJSONRequestBody = CreateGroupRequestDto

// PutApiGroupsGroupIdApplicationWildcardPlusJSONRequestBody defines body for PutApiGroupsGroupId for application/*+json ContentType.
type PutApiGroupsGroupIdApplicationWildcardPlusJSONRequestBody = UpdateGroupRequestDto

// PutApiGroupsGroupIdJSONRequestBody defines body for PutApiGroupsGroupId for application/json ContentType.
type PutApiGroupsGroupIdJSONRequestBody = UpdateGroupRequestDto

// PostApiGroupsGroupIdPaymentsDirectApplicationWildcardPlusJSONRequestBody defines body for PostApiGroupsGroupIdPaymentsDirect for application/*+json ContentType.
type PostApiGroupsGroupIdPaymentsDirectApplicationWildcardPlusJSONRequestBody = CreateDirectPaymentRequestDto

// PostApiGroupsGroupIdPaymentsDirectJSONRequestBody defines body for PostApiGroupsGroupIdPaymentsDirect for application/json ContentType.
type PostApiGroupsGroupIdPaymentsDirectJSONRequestBody = CreateDirectPaymentRequestDto

// PostApiGroupsGroupIdPaymentsExpenseApplicationWildcardPlusJSONRequestBody defines body for PostApiGroupsGroupIdPaymentsExpense for application/*+json ContentType.
type PostApiGroupsGroupIdPaymentsExpenseApplicationWildcardPlusJSONRequestBody = CreatePaymentForExpenseRequestDto

// PostApiGroupsGroupIdPaymentsExpenseJSONRequestBody defines body for PostApiGroupsGroupIdPaymentsExpense for application/json ContentType.
type PostApiGroupsGroupIdPaymentsExpenseJSONRequestBody = CreatePaymentForExpenseRequestDto

// PutApiGroupsGroupIdPaymentsPaymentIdApplicationWildcardPlusJSONRequestBody defines body for PutApiGroupsGroupIdPaymentsPaymentId for application/*+json ContentType.
type PutApiGroupsGroupIdPaymentsPaymentIdApplicationWildcardPlusJSONRequestBody = UpdatePaymentRequestDto

// PutApiGroupsGroupIdPaymentsPaymentIdJSONRequestBody defines body for PutApiGroupsGroupIdPaymentsPaymentId for application/json ContentType.
type PutApiGroupsGroupIdPaymentsPaymentIdJSONRequestBody = UpdatePaymentRequestDto

// PostApiGroupsGroupIdUsersApplicationWildcardPlusJSONRequestBody defines body for PostApiGroupsGroupIdUsers for application/*+json ContentType.
type PostApiGroupsGroupIdUsersApplicationWildcardPlusJSONRequestBody = AddGroupUserRequestDto

// PostApiGroupsGroupIdUsersJSONRequestBody defines body for PostApiGroupsGroupIdUsers for application/json ContentType.
type PostApiGroupsGroupIdUsersJSONRequestBody = AddGroupUserRequestDto

// PostApiUsersApplicationWildcardPlusJSONRequestBody defines body for PostApiUsers for application/*+json ContentType.
type PostApiUsersApplicationWildcardPlusJSONRequestBody = UserCreateRequestDto

// PostApiUsersJSONRequestBody defines body for PostApiUsers for application/json ContentType.
type PostApiUsersJSONRequestBody = UserCreateRequestDto

// PutApiUsersUserIdApplicationWildcardPlusJSONRequestBody defines body for PutApiUsersUserId for application/*+json ContentType.
type PutApiUsersUserIdApplicationWildcardPlusJSONRequestBody = UpdateUserRequestDto

// PutApiUsersUserIdJSONRequestBody defines body for PutApiUsersUserId for application/json ContentType.
type PutApiUsersUserIdJSONRequestBody = UpdateUserRequestDto

// Getter for additional properties for ProblemDetails. Returns the specified
// element and whether it was found
func (a ProblemDetails) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ProblemDetails
func (a *ProblemDetails) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ProblemDetails to handle AdditionalProperties
func (a *ProblemDetails) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ProblemDetails to handle AdditionalProperties
func (a ProblemDetails) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.Title != nil {
		object["title"], err = json.Marshal(a.Title)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'title': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
